// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v6.31.0--rc2
// source: pkg/proto/manga_service.proto

package proto

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Manga struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Title         string                 `protobuf:"bytes,2,opt,name=title,proto3" json:"title,omitempty"`
	Author        string                 `protobuf:"bytes,3,opt,name=author,proto3" json:"author,omitempty"`
	Description   string                 `protobuf:"bytes,4,opt,name=description,proto3" json:"description,omitempty"`
	Price         float32                `protobuf:"fixed32,5,opt,name=price,proto3" json:"price,omitempty"`
	Stock         int32                  `protobuf:"varint,6,opt,name=stock,proto3" json:"stock,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Manga) Reset() {
	*x = Manga{}
	mi := &file_pkg_proto_manga_service_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Manga) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Manga) ProtoMessage() {}

func (x *Manga) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_proto_manga_service_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Manga.ProtoReflect.Descriptor instead.
func (*Manga) Descriptor() ([]byte, []int) {
	return file_pkg_proto_manga_service_proto_rawDescGZIP(), []int{0}
}

func (x *Manga) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *Manga) GetTitle() string {
	if x != nil {
		return x.Title
	}
	return ""
}

func (x *Manga) GetAuthor() string {
	if x != nil {
		return x.Author
	}
	return ""
}

func (x *Manga) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

func (x *Manga) GetPrice() float32 {
	if x != nil {
		return x.Price
	}
	return 0
}

func (x *Manga) GetStock() int32 {
	if x != nil {
		return x.Stock
	}
	return 0
}

type AddMangaRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Manga         *Manga                 `protobuf:"bytes,1,opt,name=manga,proto3" json:"manga,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AddMangaRequest) Reset() {
	*x = AddMangaRequest{}
	mi := &file_pkg_proto_manga_service_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AddMangaRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AddMangaRequest) ProtoMessage() {}

func (x *AddMangaRequest) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_proto_manga_service_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AddMangaRequest.ProtoReflect.Descriptor instead.
func (*AddMangaRequest) Descriptor() ([]byte, []int) {
	return file_pkg_proto_manga_service_proto_rawDescGZIP(), []int{1}
}

func (x *AddMangaRequest) GetManga() *Manga {
	if x != nil {
		return x.Manga
	}
	return nil
}

type AddMangaResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	MangaId       string                 `protobuf:"bytes,1,opt,name=manga_id,json=mangaId,proto3" json:"manga_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AddMangaResponse) Reset() {
	*x = AddMangaResponse{}
	mi := &file_pkg_proto_manga_service_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AddMangaResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AddMangaResponse) ProtoMessage() {}

func (x *AddMangaResponse) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_proto_manga_service_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AddMangaResponse.ProtoReflect.Descriptor instead.
func (*AddMangaResponse) Descriptor() ([]byte, []int) {
	return file_pkg_proto_manga_service_proto_rawDescGZIP(), []int{2}
}

func (x *AddMangaResponse) GetMangaId() string {
	if x != nil {
		return x.MangaId
	}
	return ""
}

type EditMangaRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Manga         *Manga                 `protobuf:"bytes,1,opt,name=manga,proto3" json:"manga,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *EditMangaRequest) Reset() {
	*x = EditMangaRequest{}
	mi := &file_pkg_proto_manga_service_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *EditMangaRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EditMangaRequest) ProtoMessage() {}

func (x *EditMangaRequest) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_proto_manga_service_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use EditMangaRequest.ProtoReflect.Descriptor instead.
func (*EditMangaRequest) Descriptor() ([]byte, []int) {
	return file_pkg_proto_manga_service_proto_rawDescGZIP(), []int{3}
}

func (x *EditMangaRequest) GetManga() *Manga {
	if x != nil {
		return x.Manga
	}
	return nil
}

type EditMangaResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *EditMangaResponse) Reset() {
	*x = EditMangaResponse{}
	mi := &file_pkg_proto_manga_service_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *EditMangaResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EditMangaResponse) ProtoMessage() {}

func (x *EditMangaResponse) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_proto_manga_service_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use EditMangaResponse.ProtoReflect.Descriptor instead.
func (*EditMangaResponse) Descriptor() ([]byte, []int) {
	return file_pkg_proto_manga_service_proto_rawDescGZIP(), []int{4}
}

func (x *EditMangaResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

type ListMangasRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Page          int32                  `protobuf:"varint,1,opt,name=page,proto3" json:"page,omitempty"`
	Limit         int32                  `protobuf:"varint,2,opt,name=limit,proto3" json:"limit,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListMangasRequest) Reset() {
	*x = ListMangasRequest{}
	mi := &file_pkg_proto_manga_service_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListMangasRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListMangasRequest) ProtoMessage() {}

func (x *ListMangasRequest) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_proto_manga_service_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListMangasRequest.ProtoReflect.Descriptor instead.
func (*ListMangasRequest) Descriptor() ([]byte, []int) {
	return file_pkg_proto_manga_service_proto_rawDescGZIP(), []int{5}
}

func (x *ListMangasRequest) GetPage() int32 {
	if x != nil {
		return x.Page
	}
	return 0
}

func (x *ListMangasRequest) GetLimit() int32 {
	if x != nil {
		return x.Limit
	}
	return 0
}

type ListMangasResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Mangas        []*Manga               `protobuf:"bytes,1,rep,name=mangas,proto3" json:"mangas,omitempty"`
	Total         int32                  `protobuf:"varint,2,opt,name=total,proto3" json:"total,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListMangasResponse) Reset() {
	*x = ListMangasResponse{}
	mi := &file_pkg_proto_manga_service_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListMangasResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListMangasResponse) ProtoMessage() {}

func (x *ListMangasResponse) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_proto_manga_service_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListMangasResponse.ProtoReflect.Descriptor instead.
func (*ListMangasResponse) Descriptor() ([]byte, []int) {
	return file_pkg_proto_manga_service_proto_rawDescGZIP(), []int{6}
}

func (x *ListMangasResponse) GetMangas() []*Manga {
	if x != nil {
		return x.Mangas
	}
	return nil
}

func (x *ListMangasResponse) GetTotal() int32 {
	if x != nil {
		return x.Total
	}
	return 0
}

type CheckMangaAvailabilityRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	MangaId       string                 `protobuf:"bytes,1,opt,name=manga_id,json=mangaId,proto3" json:"manga_id,omitempty"`
	Quantity      int32                  `protobuf:"varint,2,opt,name=quantity,proto3" json:"quantity,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CheckMangaAvailabilityRequest) Reset() {
	*x = CheckMangaAvailabilityRequest{}
	mi := &file_pkg_proto_manga_service_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CheckMangaAvailabilityRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CheckMangaAvailabilityRequest) ProtoMessage() {}

func (x *CheckMangaAvailabilityRequest) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_proto_manga_service_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CheckMangaAvailabilityRequest.ProtoReflect.Descriptor instead.
func (*CheckMangaAvailabilityRequest) Descriptor() ([]byte, []int) {
	return file_pkg_proto_manga_service_proto_rawDescGZIP(), []int{7}
}

func (x *CheckMangaAvailabilityRequest) GetMangaId() string {
	if x != nil {
		return x.MangaId
	}
	return ""
}

func (x *CheckMangaAvailabilityRequest) GetQuantity() int32 {
	if x != nil {
		return x.Quantity
	}
	return 0
}

type CheckMangaAvailabilityResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Available     bool                   `protobuf:"varint,1,opt,name=available,proto3" json:"available,omitempty"`
	Stock         int32                  `protobuf:"varint,2,opt,name=stock,proto3" json:"stock,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CheckMangaAvailabilityResponse) Reset() {
	*x = CheckMangaAvailabilityResponse{}
	mi := &file_pkg_proto_manga_service_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CheckMangaAvailabilityResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CheckMangaAvailabilityResponse) ProtoMessage() {}

func (x *CheckMangaAvailabilityResponse) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_proto_manga_service_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CheckMangaAvailabilityResponse.ProtoReflect.Descriptor instead.
func (*CheckMangaAvailabilityResponse) Descriptor() ([]byte, []int) {
	return file_pkg_proto_manga_service_proto_rawDescGZIP(), []int{8}
}

func (x *CheckMangaAvailabilityResponse) GetAvailable() bool {
	if x != nil {
		return x.Available
	}
	return false
}

func (x *CheckMangaAvailabilityResponse) GetStock() int32 {
	if x != nil {
		return x.Stock
	}
	return 0
}

var File_pkg_proto_manga_service_proto protoreflect.FileDescriptor

const file_pkg_proto_manga_service_proto_rawDesc = "" +
	"\n" +
	"\x1dpkg/proto/manga_service.proto\x12\x05proto\"\x93\x01\n" +
	"\x05Manga\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x14\n" +
	"\x05title\x18\x02 \x01(\tR\x05title\x12\x16\n" +
	"\x06author\x18\x03 \x01(\tR\x06author\x12 \n" +
	"\vdescription\x18\x04 \x01(\tR\vdescription\x12\x14\n" +
	"\x05price\x18\x05 \x01(\x02R\x05price\x12\x14\n" +
	"\x05stock\x18\x06 \x01(\x05R\x05stock\"5\n" +
	"\x0fAddMangaRequest\x12\"\n" +
	"\x05manga\x18\x01 \x01(\v2\f.proto.MangaR\x05manga\"-\n" +
	"\x10AddMangaResponse\x12\x19\n" +
	"\bmanga_id\x18\x01 \x01(\tR\amangaId\"6\n" +
	"\x10EditMangaRequest\x12\"\n" +
	"\x05manga\x18\x01 \x01(\v2\f.proto.MangaR\x05manga\"-\n" +
	"\x11EditMangaResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\"=\n" +
	"\x11ListMangasRequest\x12\x12\n" +
	"\x04page\x18\x01 \x01(\x05R\x04page\x12\x14\n" +
	"\x05limit\x18\x02 \x01(\x05R\x05limit\"P\n" +
	"\x12ListMangasResponse\x12$\n" +
	"\x06mangas\x18\x01 \x03(\v2\f.proto.MangaR\x06mangas\x12\x14\n" +
	"\x05total\x18\x02 \x01(\x05R\x05total\"V\n" +
	"\x1dCheckMangaAvailabilityRequest\x12\x19\n" +
	"\bmanga_id\x18\x01 \x01(\tR\amangaId\x12\x1a\n" +
	"\bquantity\x18\x02 \x01(\x05R\bquantity\"T\n" +
	"\x1eCheckMangaAvailabilityResponse\x12\x1c\n" +
	"\tavailable\x18\x01 \x01(\bR\tavailable\x12\x14\n" +
	"\x05stock\x18\x02 \x01(\x05R\x05stock2\xb5\x02\n" +
	"\fMangaService\x12;\n" +
	"\bAddManga\x12\x16.proto.AddMangaRequest\x1a\x17.proto.AddMangaResponse\x12>\n" +
	"\tEditManga\x12\x17.proto.EditMangaRequest\x1a\x18.proto.EditMangaResponse\x12A\n" +
	"\n" +
	"ListMangas\x12\x18.proto.ListMangasRequest\x1a\x19.proto.ListMangasResponse\x12e\n" +
	"\x16CheckMangaAvailability\x12$.proto.CheckMangaAvailabilityRequest\x1a%.proto.CheckMangaAvailabilityResponseB1Z/github.com/bhanot-99/KuroPage/Backend/pkg/protob\x06proto3"

var (
	file_pkg_proto_manga_service_proto_rawDescOnce sync.Once
	file_pkg_proto_manga_service_proto_rawDescData []byte
)

func file_pkg_proto_manga_service_proto_rawDescGZIP() []byte {
	file_pkg_proto_manga_service_proto_rawDescOnce.Do(func() {
		file_pkg_proto_manga_service_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_pkg_proto_manga_service_proto_rawDesc), len(file_pkg_proto_manga_service_proto_rawDesc)))
	})
	return file_pkg_proto_manga_service_proto_rawDescData
}

var file_pkg_proto_manga_service_proto_msgTypes = make([]protoimpl.MessageInfo, 9)
var file_pkg_proto_manga_service_proto_goTypes = []any{
	(*Manga)(nil),                          // 0: proto.Manga
	(*AddMangaRequest)(nil),                // 1: proto.AddMangaRequest
	(*AddMangaResponse)(nil),               // 2: proto.AddMangaResponse
	(*EditMangaRequest)(nil),               // 3: proto.EditMangaRequest
	(*EditMangaResponse)(nil),              // 4: proto.EditMangaResponse
	(*ListMangasRequest)(nil),              // 5: proto.ListMangasRequest
	(*ListMangasResponse)(nil),             // 6: proto.ListMangasResponse
	(*CheckMangaAvailabilityRequest)(nil),  // 7: proto.CheckMangaAvailabilityRequest
	(*CheckMangaAvailabilityResponse)(nil), // 8: proto.CheckMangaAvailabilityResponse
}
var file_pkg_proto_manga_service_proto_depIdxs = []int32{
	0, // 0: proto.AddMangaRequest.manga:type_name -> proto.Manga
	0, // 1: proto.EditMangaRequest.manga:type_name -> proto.Manga
	0, // 2: proto.ListMangasResponse.mangas:type_name -> proto.Manga
	1, // 3: proto.MangaService.AddManga:input_type -> proto.AddMangaRequest
	3, // 4: proto.MangaService.EditManga:input_type -> proto.EditMangaRequest
	5, // 5: proto.MangaService.ListMangas:input_type -> proto.ListMangasRequest
	7, // 6: proto.MangaService.CheckMangaAvailability:input_type -> proto.CheckMangaAvailabilityRequest
	2, // 7: proto.MangaService.AddManga:output_type -> proto.AddMangaResponse
	4, // 8: proto.MangaService.EditManga:output_type -> proto.EditMangaResponse
	6, // 9: proto.MangaService.ListMangas:output_type -> proto.ListMangasResponse
	8, // 10: proto.MangaService.CheckMangaAvailability:output_type -> proto.CheckMangaAvailabilityResponse
	7, // [7:11] is the sub-list for method output_type
	3, // [3:7] is the sub-list for method input_type
	3, // [3:3] is the sub-list for extension type_name
	3, // [3:3] is the sub-list for extension extendee
	0, // [0:3] is the sub-list for field type_name
}

func init() { file_pkg_proto_manga_service_proto_init() }
func file_pkg_proto_manga_service_proto_init() {
	if File_pkg_proto_manga_service_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_pkg_proto_manga_service_proto_rawDesc), len(file_pkg_proto_manga_service_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   9,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_pkg_proto_manga_service_proto_goTypes,
		DependencyIndexes: file_pkg_proto_manga_service_proto_depIdxs,
		MessageInfos:      file_pkg_proto_manga_service_proto_msgTypes,
	}.Build()
	File_pkg_proto_manga_service_proto = out.File
	file_pkg_proto_manga_service_proto_goTypes = nil
	file_pkg_proto_manga_service_proto_depIdxs = nil
}
